import { ITable } from './Table';

const base: ITable = {
  columns: [
    {
      header: '지역상품권',
      name: 'gift',
      link: {
        pathname: '/local',
        query: {},
      },
    },
    {
      header: '시/도',
      name: 'sido',
    },
    {
      header: '지자체',
      name: 'local',
    },
    {
      header: '주담당자',
      name: 'mainPerson',
    },
    {
      header: '부담당자',
      name: 'subPerson',
    },
    {
      header: '상태',
      name: 'status',
    },
    {
      header: '등록자',
      name: 'registrant',
    },
    {
      header: '등록일',
      name: 'registrationDate',
    },
  ],
  items: [
    {
      id: 1,
      gift: '광명사랑상품권(L426)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 2,
      gift: '광명사랑상품권(L427)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 3,
      gift: '광명사랑상품권(L428)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 4,
      gift: '광명사랑상품권(L429)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 5,
      gift: '광명사랑상품권(L430)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 6,
      gift: '광명사랑상품권(L431)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 7,
      gift: '광명사랑상품권(L432)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 8,
      gift: '광명사랑상품권(L433)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 9,
      gift: '광명사랑상품권(L434)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 10,
      gift: '광명사랑상품권(L435)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
    {
      id: 111,
      gift: '광명사랑상품권(L436)',
      sido: '전라남도',
      local: '광양시',
      mainPerson: '홍길동',
      subPerson: '홍길동',
      status: '승인',
      registrant: '최영규',
      registrationDate: '2022-08-05',
    },
  ],
};

export const mockProps = {
  base,
};
